server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vending20200303?serverTimezone=GMT%2B2
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver   # mysql-connector-java版本低于6才能用 com.mysql.jdbc.Driver，低于6才需要url显式禁用SSL

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  type-aliases-package: cn.vincent.easycode.entity