-- CREATE TABLE:MODIFY RECORD LOG
-- DROP TABLE IF EXISTS MOD_CHARACTER_LOG;
CREATE TABLE IF NOT EXISTS MOD_CHARACTER_LOG
(
SEQ BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
EXEC_PRO VARCHAR(30),
EXEC_SQL VARCHAR(200),
MOD_TABLE VARCHAR(30),
MOD_COLUMN VARCHAR(30),
CREATE_TIEM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

-- CREATE PROCEDURE:MODIFY TABLE CHARACTER
DROP PROCEDURE IF EXISTS PR_MOD_UAP_TABLE_CHARACTER;
DELIMITER$$
CREATE PROCEDURE PR_MOD_UAP_TABLE_CHARACTER
()
BEGIN
    DECLARE V_SQL VARCHAR(200);
    DECLARE TAB_NAME VARCHAR(30);
    DECLARE DONE INT DEFAULT FALSE;
    DECLARE TAB_CURSOR CURSOR FOR (SELECT T.TABLE_NAME FROM INFORMATION_SCHEMA.`TABLES` T
WHERE T.TABLE_SCHEMA=DATABASE() AND t.TABLE_TYPE='BASE TABLE' AND T.TABLE_COLLATION IN ('utf8_bin','utf8_general_ci'));
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
    OPEN TAB_CURSOR;
      TABLOOP: LOOP
        FETCH TAB_CURSOR INTO TAB_NAME;
        IF DONE THEN
          LEAVE TABLOOP;
        END IF;
				-- MODIFY TABLE CHARACTER
				SET V_SQL=CONCAT('ALTER TABLE `',TAB_NAME,'` DEFAULT CHARACTER SET UTF8MB4');
        SET @V_SQL=V_SQL;
        PREPARE STMT FROM @V_SQL;
        EXECUTE STMT;
        DEALLOCATE PREPARE STMT;
				INSERT INTO MOD_CHARACTER_LOG(EXEC_PRO,EXEC_SQL,MOD_TABLE) VALUES('PR_MOD_UAP_TABLE_CHARACTER',V_SQL,TAB_NAME);
				COMMIT;
      END LOOP TABLOOP;
    CLOSE TAB_CURSOR;
END$$
DELIMITER ;

-- CREATE PROCEDURE:MODIFY COLUMN CHARACTER
DROP PROCEDURE IF EXISTS PR_MOD_UAP_COLUMN_CHARACTER;
DELIMITER$$
CREATE PROCEDURE PR_MOD_UAP_COLUMN_CHARACTER
()
BEGIN
    DECLARE V_SQL VARCHAR(200);
    DECLARE TAB_NAME VARCHAR(30);
		DECLARE COL_NAME VARCHAR(30);
		DECLARE COLLA_NAME VARCHAR(30);
		DECLARE CHAR_NAME VARCHAR(30);
    DECLARE DONE INT DEFAULT FALSE;
    DECLARE TAB_CURSOR CURSOR FOR (SELECT T.TABLE_NAME,T.COLUMN_NAME,T.COLLATION_NAME,CASE WHEN t.DATA_TYPE = 'varchar' OR t.DATA_TYPE = 'char' THEN  CONCAT(t.DATA_TYPE,'(',t.CHARACTER_MAXIMUM_LENGTH,')') ELSE t.DATA_TYPE END
FROM INFORMATION_SCHEMA.`COLUMNS` T
INNER JOIN information_schema.`TABLES` a on a.TABLE_NAME=t.TABLE_NAME
WHERE a.TABLE_SCHEMA=DATABASE()
  AND a.TABLE_TYPE='BASE TABLE'
  AND T.TABLE_SCHEMA=DATABASE()
  AND T.CHARACTER_SET_NAME='utf8');
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
    OPEN TAB_CURSOR;
      TABLOOP: LOOP
        FETCH TAB_CURSOR INTO TAB_NAME,COL_NAME,COLLA_NAME,CHAR_NAME;
        IF DONE THEN
          LEAVE TABLOOP;
        END IF;
				-- MODIFY COLUMN CHARACTER
				IF COLLA_NAME='utf8_bin' THEN
				    SET COLLA_NAME='utf8mb4_bin';
				ELSE
				    SET COLLA_NAME=(SELECT t.DEFAULT_COLLATE_NAME FROM information_schema.CHARACTER_SETS t WHERE t.CHARACTER_SET_NAME='utf8mb4');
				END IF;
				SET V_SQL=CONCAT('ALTER TABLE `',TAB_NAME,'` CHANGE `',COL_NAME,'` `',COL_NAME,'` ',CHAR_NAME,' CHARACTER SET UTF8MB4 COLLATE ',COLLA_NAME);
        SET @V_SQL=V_SQL;
        PREPARE STMT FROM @V_SQL;
        EXECUTE STMT;
        DEALLOCATE PREPARE STMT;
				INSERT INTO MOD_CHARACTER_LOG(EXEC_PRO,EXEC_SQL,MOD_TABLE,MOD_COLUMN) VALUES('PR_MOD_UAP_COLUMN_CHARACTER',V_SQL,TAB_NAME,COL_NAME);
				COMMIT;
      END LOOP TABLOOP;
    CLOSE TAB_CURSOR;
END$$
DELIMITER ;

-- EXEC PROCEDURE TO MODIFY CHARACTER
SET FOREIGN_KEY_CHECKS = 0;
CALL PR_MOD_UAP_TABLE_CHARACTER();
CALL PR_MOD_UAP_COLUMN_CHARACTER();
SET FOREIGN_KEY_CHECKS = 1;

-- QUERY MODIFY LOG TABLE
SELECT * FROM MOD_CHARACTER_LOG;



