server:
  port: 8000

#数据库连接的全局配置
#mybatis.configuration.cache-enabled: true
#mybatis.configuration.local-cache-scope: session

#连接数据库1配置
#spring.user.datasourceType: com.alibaba.druid.pool.DruidDataSource
#spring.user.datasource.url: jdbc:mysql://127.0.0.1:3306/pingyougou?serverTimezone=UTC
#spring.user.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#spring.user.datasource.username: root
#spring.user.datasource.password: 123
#logging.leve.com.yin.databaseproject.dao: debug


#连接数据库2配置
#spring.item.datasourceType: com.alibaba.druid.pool.DruidDataSource
#spring.item.datasource.url: jdbc:mysql://127.0.0.1:3306/mybatis?serverTimezone=UTC
#spring.item.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#spring.item.datasource.username: root
#spring.item.datasource.password: 123
#spring:
#  profiles: user8000
#server:
#  port: 8000
#---
#spring:
#  profiles: user8001
#server:
#  port: 8001
spring:
  datasource:
    master:
      # url: jdbc:mysql://192.168.80.35:6446/centlec?serverTimezone=GMT%2B2&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      url: jdbc:mysql://192.168.80.15:3306/centlec?serverTimezone=GMT%2B2&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#      url: jdbc:mysql://192.168.80.36:3306/ctlctest?serverTimezone=GMT%2B2&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: Ctlcuat1
      password: Hex123@0
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
    other:
      # url: jdbc:sqlserver://192.168.108.12:1433;DatabaseName=hxdb20200113
      url: jdbc:sqlserver://192.168.108.11:1433;DatabaseName=hxdb
      username: pns
      password: pnssnp
      #使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  application:
    name: SpringQuartzDB
mybatis:
  type-aliases-package: cn.vincent.pojo
  mapper-locations: classpath:cn/vincent/dao/**/*.xml
# 将文件名改为log4j2-spring.xml，则此处省略配置且一样配置生效，但是启动log4j2还是会报找不到配置文件，可能是bug
#logging:
#  config: classpath:log4j2.xml
