server:
  port: 8000

#数据库连接的全局配置
#mybatis.configuration.cache-enabled: true
#mybatis.configuration.local-cache-scope: session

#连接数据库1配置
#spring.user.datasourceType: com.alibaba.druid.pool.DruidDataSource
#spring.user.datasource.url: jdbc:mysql://127.0.0.1:3306/pingyougou?serverTimezone=UTC
#spring.user.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#spring.user.datasource.username: root
#spring.user.datasource.password: 123
#logging.leve.com.yin.databaseproject.dao: debug


#连接数据库2配置
#spring.item.datasourceType: com.alibaba.druid.pool.DruidDataSource
#spring.item.datasource.url: jdbc:mysql://127.0.0.1:3306/mybatis?serverTimezone=UTC
#spring.item.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#spring.item.datasource.username: root
#spring.item.datasource.password: 123
#spring:
#  profiles: user8000
#server:
#  port: 8000
#---
#spring:
#  profiles: user8001
#server:
#  port: 8001
spring:
  datasource:
    master:
      # url: jdbc:mysql://192.168.80.35:6446/centlec?serverTimezone=GMT%2B2&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      url: jdbc:mysql://localhost:3306/centlec?serverTimezone=GMT%2B2&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#      url: jdbc:mysql://192.168.80.36:3306/ctlctest?serverTimezone=GMT%2B2&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: Ctlcuat1
      password: Hex123@0
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      ########### 配置druid连接池
      initial-size: 5
      # 获取连接等待超时的时间10s
      max-wait: 10000
      min-idle: 5
      max-active: 50
      max-idle: 50
      # 验证连接是否有效
      validation-query: SELECT 1
      # 允许连接被空闲连接回收器检测：即检测失败会被从池中移除
      test-while-idle: true
      # 是否从池中取出连接前进行检测，如果检测失败则从池中移除该连接，并尝试取出另一个（为了效率，可以设为默认false）
      test-on-borrow: true
      # 是否在归还到池中之前进行检测
      test-on-return: false
      # 间隔30min去检测需要驱逐/关闭的空闲连接
      time-between-eviction-runs-millis: 18800
      # 一个连接在池中最小的生存时间：30min
      min-evictable-idle-time-millis: 1800000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
    other:
      # DB-1
      url: jdbc:sqlserver://192.168.108.11:1433;DatabaseName=hxdb
      username: pns
      password: pnssnp
      # DB-2
      # url: jdbc:sqlserver://192.168.108.12:1433;DatabaseName=hxdb20200113
      # username: pns
      # password: pnssnp
      # DB-TEST
      # url: jdbc:sqlserver://192.168.108.152:1433;DatabaseName=hxdb
      # username: pns
      # password: pnspns
      #使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      ########### 配置druid连接池
      initial-size: 5
      # 获取连接等待超时的时间10s
      max-wait: 10000
      min-idle: 5
      max-active: 50
      max-idle: 50
      # 验证连接是否有效
      validation-query: SELECT 1
      # 允许连接被空闲连接回收器检测：即检测失败会被从池中移除
      test-while-idle: true
      # 是否从池中取出连接前进行检测，如果检测失败则从池中移除该连接，并尝试取出另一个（为了效率，可以设为默认false）
      test-on-borrow: true
      # 是否在归还到池中之前进行检测
      test-on-return: false
      # 间隔30min去检测需要驱逐/关闭的空闲连接
      time-between-eviction-runs-millis: 18800
      # 一个连接在池中最小的生存时间：30min
      min-evictable-idle-time-millis: 1800000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  application:
    name: SpringQuartzDB
mybatis:
  type-aliases-package: cn.vincent.pojo
  mapper-locations: classpath:cn/vincent/dao/**/*.xml
# 将文件名改为log4j2-spring.xml，则此处省略配置且一样配置生效，但是启动log4j2还是会报找不到配置文件，可能是bug
#logging:
#  config: classpath:log4j2.xml
