CREATE TABLE IF NOT EXISTS `VD_E_BILL_PKG_VER_SNAP` (
    `LESSEE_ID` BIGINT(20),
    `VER_ID` DECIMAL(16,0) NOT NULL,
    `PKG_ID` DECIMAL(16,0),
	`CALC_ID` DECIMAL(16,0),
    `VER_NO` VARCHAR(16),
    `VER_NAME` VARCHAR(64),
    `CHARGE_ONCE_LIMIT` DECIMAL(15,0),
	`CHARGE_CNT_LIMIT` DECIMAL(15,0),
    `REMARK`  VARCHAR(256),
    `STATUS` VARCHAR(8),
    `ACTIVE_SINCE` DATETIME,
	`ACTIVE_UNTIL` DATETIME,
	`ISSUE_DATE` DATETIME,
    `OPERATOR_ID` BIGINT(20),
    `OPERAROR_TIME` DATETIME ,
    `TI` DATETIME ,
	`LAUNCH_DATE` DATETIME ,
  PRIMARY KEY (`VER_ID`,`CALC_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 ;

CALL PR_MOD_COL('VD_E_BILL_PKG_VER_SNAP','MODIFY','CALC_ID','DECIMAL(16,0)','','NOT NULL','');
CALL PR_MOD_IDX_CONS('VD_E_BILL_PKG_VER_SNAP','DROP','P','','VER_ID, CALC_ID','','', '', '');
CALL PR_MOD_IDX_CONS('VD_E_BILL_PKG_VER_SNAP','ADD','P','PK_VD_E_BILL_PKG_VER_SNAP','CALC_ID','','', '', '');
CALL PR_MOD_COL('VD_E_BILL_PKG_VER_SNAP','MODIFY','VER_ID','DECIMAL(16,0)','','NULL','');
