
package cn.vincent.xmlvend.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "xmlvendFaultResp", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema")
public class NRSFaultResponseSoapOut
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private XMLVendFaultResp faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NRSFaultResponseSoapOut(String message, XMLVendFaultResp faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NRSFaultResponseSoapOut(String message, XMLVendFaultResp faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cn.vincent.xmlvend.client.XMLVendFaultResp
     */
    public XMLVendFaultResp getFaultInfo() {
        return faultInfo;
    }

}
