
package cn.vincent.xmlvend.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "XMLVendServiceSoap", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/service/2.1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface XMLVendServiceSoap {


    /**
     * Vend a credit token, any other tokens required and return all information
     * 
     * @param messagePart
     * @return
     *     returns cn.vincent.xmlvend.client.CreditVendResp
     * @throws NRSFaultResponseSoapOut
     */
    @WebMethod(operationName = "CreditVendRequest")
    @WebResult(name = "creditVendResp", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", partName = "messagePart")
    public CreditVendResp creditVendRequest(
            @WebParam(name = "creditVendReq", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", partName = "messagePart")
                    CreditVendReq messagePart)
        throws NRSFaultResponseSoapOut
    ;

    /**
     * Confirm customer details from the information supplied.
     * 
     * @param messagePart
     * @return
     *     returns cn.vincent.xmlvend.client.ConfirmCustomerResp
     * @throws NRSFaultResponseSoapOut
     */
    @WebMethod(operationName = "ConfirmCustomerRequest")
    @WebResult(name = "confirmCustomerResp", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", partName = "messagePart")
    public ConfirmCustomerResp confirmCustomerRequest(
            @WebParam(name = "confirmCustomerReq", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", partName = "messagePart")
                    ConfirmCustomerReq messagePart)
        throws NRSFaultResponseSoapOut
    ;

    /**
     * Trial Vend a credit token and return cost of such a token.
     * 
     * @param messagePart
     * @return
     *     returns cn.vincent.xmlvend.client.TrialCreditVendResp
     * @throws NRSFaultResponseSoapOut
     */
    @WebMethod(operationName = "TrialCreditVendRequest")
    @WebResult(name = "trialCreditVendResp", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", partName = "messagePart")
    public TrialCreditVendResp trialCreditVendRequest(
            @WebParam(name = "trialCreditVendReq", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", partName = "messagePart")
                    TrialCreditVendReq messagePart)
        throws NRSFaultResponseSoapOut
    ;

    /**
     * Advice on the preceding Vend Request of type, confirm, reverse or AutoReprint.
     * 
     * @param messagePart
     * @return
     *     returns cn.vincent.xmlvend.client.AdviceResp
     * @throws NRSFaultResponseSoapOut
     */
    @WebMethod(operationName = "AdviceRequest")
    @WebResult(name = "adviceResp", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema", partName = "messagePart")
    public AdviceResp adviceRequest(
            @WebParam(name = "adviceReq", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema", partName = "messagePart")
                    AdviceReq messagePart)
        throws NRSFaultResponseSoapOut
    ;

    /**
     * Confirm login details from the information supplied
     * 
     * @param messagePart
     * @return
     *     returns cn.vincent.xmlvend.client.LoginUser
     * @throws NRSFaultResponseSoapOut
     */
    @WebMethod(operationName = "LoginRequest")
    @WebResult(name = "user", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", partName = "messagePart")
    public LoginUser loginRequest(
            @WebParam(name = "loginReq", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", partName = "messagePart")
                    LoginReq messagePart)
        throws NRSFaultResponseSoapOut
    ;

    /**
     * Reprint X number transactions token and return all information
     * 
     * @param messagePart
     * @return
     *     returns cn.vincent.xmlvend.client.ReprintResp
     * @throws NRSFaultResponseSoapOut
     */
    @WebMethod(operationName = "ReprintRequest")
    @WebResult(name = "reprintResp", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", partName = "messagePart")
    public ReprintResp reprintRequest(
            @WebParam(name = "reprintReq", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", partName = "messagePart")
                    ReprintReq messagePart)
        throws NRSFaultResponseSoapOut
    ;

    /**
     * Get meter balance
     * 
     * @param messagePart
     * @return
     *     returns cn.vincent.xmlvend.client.GetMeterBalanceResponse
     * @throws NRSFaultResponseSoapOut
     */
    @WebMethod(operationName = "GetMeterBalance")
    @WebResult(name = "getMeterBalanceResponse", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema", partName = "messagePart")
    public GetMeterBalanceResponse getMeterBalance(
            @WebParam(name = "getMeterBalanceReq", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/meter/2.1/schema", partName = "messagePart")
                    ConfirmMeterReq messagePart)
        throws NRSFaultResponseSoapOut
    ;

    /**
     * Get order status
     * 
     * @param messagePart
     * @return
     *     returns cn.vincent.xmlvend.client.GetOrderStatusResp
     * @throws NRSFaultResponseSoapOut
     */
    @WebMethod(operationName = "GetOrderStatus")
    @WebResult(name = "getOrderStatusResp", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema", partName = "messagePart")
    public GetOrderStatusResp getOrderStatus(
            @WebParam(name = "getOrderStatusReq", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/base/2.1/schema", partName = "messagePart")
                    GetOrderStatusReq messagePart)
        throws NRSFaultResponseSoapOut
    ;

    /**
     * Vend a FBE credit token, any other tokens required and return all information
     * 
     * @param messagPart
     * @return
     *     returns cn.vincent.xmlvend.client.FBEResp
     * @throws NRSFaultResponseSoapOut
     */
    @WebMethod(operationName = "FBERequest")
    @WebResult(name = "fbeResp", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", partName = "messagePart")
    public FBEResp fbeRequest(
            @WebParam(name = "fbeReq", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/revenue/2.1/schema", partName = "messagPart")
                    FBEReq messagPart)
        throws NRSFaultResponseSoapOut
    ;

}
