
package cn.vincent.xmlvend.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * NRS Compliant Online Vending Service.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "XMLVendService2.1", targetNamespace = "http://www.nrs.eskom.co.za/xmlvend/service/2.1", wsdlLocation = "file:/D:/xmlvend.wsdl")
public class XMLVendService21
    extends Service
{

    private final static URL XMLVENDSERVICE21_WSDL_LOCATION;
    private final static WebServiceException XMLVENDSERVICE21_EXCEPTION;
    private final static QName XMLVENDSERVICE21_QNAME = new QName("http://www.nrs.eskom.co.za/xmlvend/service/2.1", "XMLVendService2.1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/xmlvend.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XMLVENDSERVICE21_WSDL_LOCATION = url;
        XMLVENDSERVICE21_EXCEPTION = e;
    }

    public XMLVendService21() {
        super(__getWsdlLocation(), XMLVENDSERVICE21_QNAME);
    }

    public XMLVendService21(WebServiceFeature... features) {
        super(__getWsdlLocation(), XMLVENDSERVICE21_QNAME, features);
    }

    public XMLVendService21(URL wsdlLocation) {
        super(wsdlLocation, XMLVENDSERVICE21_QNAME);
    }

    public XMLVendService21(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XMLVENDSERVICE21_QNAME, features);
    }

    public XMLVendService21(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XMLVendService21(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns XMLVendServiceSoap
     */
    @WebEndpoint(name = "XMLVendServicePort")
    public XMLVendServiceSoap getXMLVendServicePort() {

        return super.getPort(new QName("http://www.nrs.eskom.co.za/xmlvend/service/2.1", "XMLVendServicePort"), XMLVendServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XMLVendServiceSoap
     */
    @WebEndpoint(name = "XMLVendServicePort")
    public XMLVendServiceSoap getXMLVendServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.nrs.eskom.co.za/xmlvend/service/2.1", "XMLVendServicePort"), XMLVendServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XMLVENDSERVICE21_EXCEPTION!= null) {
            throw XMLVENDSERVICE21_EXCEPTION;
        }
        return XMLVENDSERVICE21_WSDL_LOCATION;
    }

}
