/*其他计费明细 VD_E_CALC_DETAIL*/
CREATE TABLE IF NOT EXISTS VD_E_CALC_DETAIL
(
   LESSEE_ID            bigint(20) comment '租户ID',
   CALC_DETAIL_ID       NUMERIC(16,0)  not null,
   CALC_ID              NUMERIC(16,0),
   ITEM_ID              NUMERIC(16,0)  not null,
   CALC_VALUE           NUMERIC(18,2),
   CALC_AMT             NUMERIC(18,2),
   PRICE_FLAG           varchar(8),
   TV		DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (CALC_DETAIL_ID, TV)
)
ENGINE = INNODB CHARACTER SET = UTF8MB4 COLLATE = UTF8MB4_GENERAL_CI
PARTITION BY RANGE (TO_DAYS(TV))(PARTITION PMAX VALUES LESS THAN (MAXVALUE));